baseurl = "/"
languageCode = "en-us"
# 仅在你将主题保存在 `themes` 目录中时添加此项。
# 如果你使用主题作为远程 Hugo Module，请移除此项。
theme = "terminal"
paginate = 5

[params]
  # 你的主要内容的目录名称（默认是 `content/posts`）。
  # 设置的内容列表将显示在你的首页（baseurl）上。
  contentTypeName = "posts"

  # 如果你将此项设置为 0，则只会显示子菜单触发器。
  showMenuItems = 2

  # 显示语言选择器
  showLanguageSelector = false

  # 设置主题为全屏宽度
  fullWidthTheme = false

  # 居中主题，使用默认宽度
  centerTheme = false

  # 如果你的资源目录中包含名为 `cover.(jpg|png|webp)` 的图像，
  # 那么该文件将自动用作封面。
  # 通过此选项，你不需要在前置参数中设置 `cover`。
  autoCover = true

  # 设置文章显示最后更新时间
  # 如果你使用 git，可以将 `enableGitInfo` 设置为 `true`，然后文章将自动获取最后更新时间。
  showLastUpdated = false

  # 为最后更新日期提供一个前缀字符串。默认情况下，它看起来像这样：2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # 是否显示页面估计阅读时间
  # readingTime = false # 默认

  # 是否显示目录
  # 可以在页面的前置参数中覆盖
  # Toc = false # 默认

  # 设置目录的标题
  # 可以在页面的前置参数中覆盖
  # TocTitle = "Table of Contents" # 默认


[params.twitter]
  # 为 Twitter 卡片设置 Twitter 句柄
  # 参见 https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # 不要包含 @
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "Terminal"

    [languages.en.params]
      subtitle = "一个简单的 Hugo 复古主题"
      owner = ""
      keywords = ""
      copyright = ""
      menuMore = "显示更多"
      readMore = "阅读更多"
      readOtherPosts = "阅读其他文章"
      newerPosts = "新文章"
      olderPosts = "旧文章"
      missingContentMessage = "页面未找到..."
      missingBackButtonLabel = "返回首页"
      minuteReadingTime = "分钟阅读"
      words = "字"

      [languages.en.params.logo]
        logoText = "Terminal"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "about"
          name = "关于"
          url = "/about"
        [[languages.en.menu.main]]
          identifier = "showcase"
          name = "展示"
          url = "/showcase"

[module]
  # 如果你希望对主题进行更改并将其保存在你的仓库中，
  # 请取消注释以下行（并根据需要更正本地路径）。
  # --
  # replacements = "github.com/panr/hugo-theme-terminal/v4 -> themes/terminal"
[[module.imports]]
  path = 'github.com/panr/hugo-theme-terminal/v4'